export const Roles = Object.freeze({
  ADMIN: 'admin',
  BLOGGER: 'blogger',
  ADMIN_WEB: 'admin-web',
  ADMIN_ALMACEN: 'admin-almacen',
  OPERADOR: 'operador'
});

export const Permissions = Object.freeze({
  CREATE_USER: 'create-user',
  READ_USER: 'read-user',
  EDIT_USER: 'edit-user',
  DELETE_USER: 'delete-user',
  CREATE_POST: 'create-post',
  READ_POST: 'read-post',
  EDIT_POST: 'edit-post',
  DELETE_POST: 'delete-post',
  CREATE_TESTIMONIAL: 'create-testimonial',
  READ_TESTIMONIAL: 'read-testimonial',
  EDIT_TESTIMONIAL: 'edit-testimonial',
  DELETE_TESTIMONIAL: 'delete-testimonial',
  CREATE_PROJECT: 'create-project',
  READ_PROJECT: 'read-project',
  EDIT_PROJECT: 'edit-project',
  DELETE_PROJECT: 'delete-project',
  CREATE_SERVICE: 'create-service',
  READ_SERVICE: 'read-service',
  EDIT_SERVICE: 'edit-service',
  DELETE_SERVICE: 'delete-service',
  CREATE_REQUESICION: 'create-requesicion',
  READ_REQUESICION: 'read-requesicion',
  EDIT_REQUESICION: 'edit-requesicion',
  DELETE_REQUESICION: 'delete-requesicion',
  ACCEPT_REQUESICION: 'accept-requesicion',
  CREATE_ALMACEN: 'create-almacen',
  READ_ALMACEN: 'read-almacen',
  EDIT_ALMACEN: 'edit-almacen',
  DELETE_ALMACEN: 'delete-almacen',
});
